name: wives
description: A Terminal that is as beautiful as your wife or probably better

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xterm: ^3.4.0
  flutter_pty: ^0.3.1
  flutter_hooks: ^0.18.5+1
  collection: ^1.16.0
  window_manager: ^0.2.7
  fluentui_system_icons: ^1.1.186
  scroll_to_index: ^3.0.1
  path: ^1.8.2
  riverpod: ^2.1.1
  hooks_riverpod: ^2.1.1
  flutter_spinbox: ^0.11.0
  multi_split_view: ^2.1.0
  go_router: ^5.1.6
  tuple: ^2.0.1
  nanoid: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  ffi: ^2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Cascadia Mono
      fonts:
        - asset: fonts/CascadiaMonoPL.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
