name: wives
description: A Terminal that is as beautiful as your wife or probably better

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xterm: 3.0.6-alpha
  flutter_pty: ^0.3.0
  flutter_hooks: ^0.18.5+1
  collection: ^1.16.0
  bitsdojo_window: ^0.1.5
  fluentui_system_icons: ^1.1.181
  scroll_to_index: ^3.0.1
  path: ^1.8.2
  riverpod: ^1.0.3
  hooks_riverpod: ^1.0.4
  flutter_spinbox: ^0.9.0
  multi_split_view: ^2.1.0
  go_router: ^5.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  ffi: ^2.0.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
