app_id: A352D666-B2E1-41B4-A9AF-FA6D1DA15882
publisher: Kingkor Roy Tirtho
publisher_url: https://github.com/KRTirtho/wives
display_name: Wives
create_desktop_icon: true
install_dir_name: Wives
locales:
  - en